# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: publish-riffy

on:
  release:
    types: [published]

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: "npm"
      - name: "Install latest npm version"
        run: npm install -g npm@latest
      - name: "print Node.JS & NPM Version"
        run: node --version && npm --v
      - name: "Install packages"
        run: npm ci
      - name: "publish package"
        run: npm publish --access public
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          # NPM_CONFIG_PROVENANCE: true
